Determinism:
  seed: 42

Data:
  dataloader_pin_memory: True

Training: 
  per_device_train_batch_size: 8
  learning_rate: 2e-5
  num_train_epochs: 10

  Floating-point:
    fp16: False
    fp16_full_eval: False

Evaluation:
  per_device_eval_batch_size: 64
  evaluation_strategy: epoch

  Best_model:
    metric_for_best_model: eval_map-bioasq@10
    greater_is_better: True

Logging:
  logging_strategy: steps
  logging_first_step: True
  logging_steps: 100
  output_dir: pubmed_bert_classifier_V2
  report_to: none

  Saving:
    save_strategy: epoch
    push_to_hub: False
    save_total_limit: 3

Optimizer:    
  weight_decay: 0.01